# Generated by Django 2.2.5 on 2021-04-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': ' Drop Catageories'},
        ),
    ]
