# Generated by Django 2.2.5 on 2021-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20210504_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log in this site', verbose_name='staff status'),
        ),
    ]
